### ISSUE TITLE
Create LLaMa2 Fine-Tuning Pipeline

### ISSUE THREAD

**Issue by MaxHuber88** [yu-jeffy/profit-llm-morality#6]

**Comment by yu-jeffy** [comment]
Trained and uploaded to huggingface (private, ask for access) - https://huggingface.co/jeffzyu/llama-2-7b-chat-profit

2300 examples in training data.
Trained on A6000 on Paperspace.


Updated notebook in repo (llama_v2.ipynb)

Hallucinates a lot, trying to fix with system prompt formatting, model parameters (temp, top_k, top_p).

Training full data set now, not sure how many examples we need.
